# Generated by Django 5.2.2 on 2025-06-09 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('species', models.CharField(max_length=100)),
                ('genome_reference', models.CharField(max_length=200)),
                ('pipeline_version', models.CharField(max_length=20)),
                ('sequencing_type', models.CharField(max_length=20)),
                ('pvalue_cutoff', models.FloatField(default=0.05)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('project_size', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('session_id', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=500)),
                ('is_directory', models.BooleanField(default=False)),
                ('file_format', models.CharField(max_length=50)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsa.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsa.user'),
        ),
    ]
