# Generated by Django 5.2.1 on 2025-05-27 21:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(editable=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=100)),
                ('genome_reference', models.CharField(max_length=255)),
                ('pipeline_version', models.CharField(max_length=50)),
                ('sequencing_type', models.CharField(choices=[('single', 'Single-End'), ('paired', 'Paired-End')], default='single', max_length=20)),
                ('pvalue_cutoff', models.FloatField(default=0.05, help_text='P-value cutoff for differential expression analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('session_id', models.UUIDField(editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=255)),
                ('is_directory', models.BooleanField(default=False)),
                ('file_format', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='rsa.project')),
            ],
            options={
                'db_table': 'project_input',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='rsa.user'),
        ),
    ]
